name: PHP check syntax errors

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: overtrue/phplint@6.0.0
    - uses: php-actions/phpcs@v1
      with:
        php_version: 8.2
        path: App/        
        standard: PSR12
        args: "--runtime-set ignore_warnings_on_exit 1"
